# Generated by Django 3.0.5 on 2020-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_user_user_raw_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_button_text',
            field=models.CharField(default='No text specifies', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_message',
            field=models.TextField(default='No Messages'),
        ),
    ]
