# Generated by Django 3.0.5 on 2020-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_place_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_error_sound',
            field=models.BooleanField(default=False),
        ),
    ]
