# Generated by Django 3.0.5 on 2020-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_enable_error_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_photo_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_upload_error_message',
            field=models.TextField(default='No Messages'),
        ),
    ]
