# Generated by Django 3.0.5 on 2020-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20201103_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_upload_error_message',
            field=models.TextField(blank=True),
        ),
    ]
