# Generated by Django 3.0.5 on 2020-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20201103_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Photo_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='user_id_card_upload/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
