# Generated by Django 3.0.5 on 2020-11-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_user_photo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_voice_message',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
