# Generated by Django 3.0.5 on 2020-12-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_user_voice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trade_bonus',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
