# Generated by Django 3.0.5 on 2020-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_trade_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawRequestBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=300)),
                ('withdraw_amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
